import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import { FaMapMarkerAlt, FaUser, FaPhone, FaStickyNote, FaCompass, FaSearchLocation } from 'react-icons/fa';
import Button from '../../../shared/components/ui/Button';
import GhanaRegionSelect from './GhanaRegionSelect';

/**
 * Reusable Pickup Location Form Component
 * Used by both Create and Edit pages
 * 
 * @param {Object} initialData - Initial form data (for edit mode)
 * @param {Function} onSubmit - Submit handler
 * @param {boolean} isSubmitting - Loading state
 * @param {Function} onCancel - Cancel handler
 */
const PickupLocationForm = ({ initialData = null, onSubmit, isSubmitting = false, onCancel }) => {
  const [formData, setFormData] = useState({
    name: '',
    region: '',
    city: '',
    address: '',
    latitude: null,
    longitude: null,
    digitalAddress: '',
    contactName: '',
    contactPhone: '',
    isDefault: false,
    notes: '',
  });

  const [errors, setErrors] = useState({});
  const [isFetchingLocation, setIsFetchingLocation] = useState(false);
  const [locationError, setLocationError] = useState('');

  // Load initial data for edit mode
  useEffect(() => {
    if (initialData) {
      setFormData({
        name: initialData.name || '',
        region: initialData.region || '',
        city: initialData.city || '',
        address: initialData.address || '',
        latitude: initialData.latitude || null,
        longitude: initialData.longitude || null,
        digitalAddress: initialData.digitalAddress || '',
        contactName: initialData.contactName || '',
        contactPhone: initialData.contactPhone || '',
        isDefault: initialData.isDefault || false,
        notes: initialData.notes || '',
      });
    }
  }, [initialData]);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value,
    }));
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors((prev) => ({
        ...prev,
        [name]: null,
      }));
    }
  };

  const handleRegionChange = (e) => {
    setFormData((prev) => ({
      ...prev,
      region: e.target.value,
    }));
    if (errors.region) {
      setErrors((prev) => ({
        ...prev,
        region: null,
      }));
    }
  };

  // Get current location and generate digital address
  const getCurrentLocation = () => {
    if (!navigator.geolocation) {
      setLocationError('Geolocation is not supported by your browser');
      return;
    }

    setIsFetchingLocation(true);
    setLocationError('');

    navigator.geolocation.getCurrentPosition(
      async (position) => {
        try {
          const { latitude, longitude } = position.coords;

          // Reverse geocode to get address details
          const response = await fetch(
            `https://nominatim.openstreetmap.org/reverse?format=json&lat=${latitude}&lon=${longitude}&zoom=18&addressdetails=1`
          );

          const data = await response.json();

          if (data.error) {
            throw new Error(data.error);
          }

          // Extract address components
          const address = data.address || {};

          // Update form with location data
          setFormData((prev) => ({
            ...prev,
            city: address.city || address.town || address.village || prev.city,
            region: address.state || address.region || prev.region,
            address: address.road || address.highway || prev.address,
            latitude: latitude,
            longitude: longitude,
            // Digital address will be auto-generated by backend from coordinates
          }));
        } catch (error) {
          console.error('Reverse geocoding error:', error);
          setLocationError('Failed to get address details. Coordinates will still be saved.');
        } finally {
          setIsFetchingLocation(false);
        }
      },
      (error) => {
        let errorMessage = 'Unable to get your location. ';
        
        switch (error.code) {
          case error.PERMISSION_DENIED:
            errorMessage += 'Location access was denied. Please enable location permissions.';
            break;
          case error.POSITION_UNAVAILABLE:
            errorMessage += 'Location information is unavailable.';
            break;
          case error.TIMEOUT:
            errorMessage += 'Location request timed out. Please try again.';
            break;
          default:
            errorMessage += 'Please try again.';
            break;
        }
        
        setLocationError(errorMessage);
        setIsFetchingLocation(false);
      },
      {
        enableHighAccuracy: false,
        timeout: 15000,
        maximumAge: 60000,
      }
    );
  };

  const validate = () => {
    const newErrors = {};

    if (!formData.name.trim()) {
      newErrors.name = 'Location name is required';
    }

    if (!formData.region) {
      newErrors.region = 'Region is required';
    }

    if (!formData.city.trim()) {
      newErrors.city = 'City/Town is required';
    }

    if (!formData.address.trim()) {
      newErrors.address = 'Full address is required';
    }

    if (!formData.contactName.trim()) {
      newErrors.contactName = 'Contact person name is required';
    }

    if (!formData.contactPhone.trim()) {
      newErrors.contactPhone = 'Contact phone number is required';
    } else if (!/^[0-9+\-\s()]+$/.test(formData.contactPhone)) {
      newErrors.contactPhone = 'Please enter a valid phone number';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (validate()) {
      onSubmit(formData);
    }
  };

  return (
    <FormContainer>
      <StyledForm onSubmit={handleSubmit}>
        {/* Location Name */}
        <FormGroup>
          <Label htmlFor="name">
            <FaMapMarkerAlt /> Location Name <Required>*</Required>
          </Label>
          <Input
            id="name"
            name="name"
            type="text"
            value={formData.name}
            onChange={handleChange}
            placeholder="e.g., Main Shop, Warehouse A, Branch Office"
            disabled={isSubmitting}
            $hasError={!!errors.name}
          />
          {errors.name && <ErrorText>{errors.name}</ErrorText>}
          <HelperText>Give this location a descriptive name</HelperText>
        </FormGroup>

        {/* Region */}
        <FormGroup>
          <GhanaRegionSelect
            id="region"
            name="region"
            value={formData.region}
            onChange={handleRegionChange}
            label="Region"
            required
            disabled={isSubmitting}
            error={errors.region}
          />
        </FormGroup>

        {/* City/Town */}
        <FormGroup>
          <Label htmlFor="city">
            City/Town <Required>*</Required>
          </Label>
          <Input
            id="city"
            name="city"
            type="text"
            value={formData.city}
            onChange={handleChange}
            placeholder="e.g., Accra, Kumasi, Tamale"
            disabled={isSubmitting}
            $hasError={!!errors.city}
          />
          {errors.city && <ErrorText>{errors.city}</ErrorText>}
        </FormGroup>

        {/* Full Address */}
        <FormGroup>
          <Label htmlFor="address">
            Full Address <Required>*</Required>
          </Label>
          <TextArea
            id="address"
            name="address"
            value={formData.address}
            onChange={handleChange}
            placeholder="Street address, building name, landmark, etc."
            rows={3}
            disabled={isSubmitting}
            $hasError={!!errors.address}
          />
          {errors.address && <ErrorText>{errors.address}</ErrorText>}
          <HelperText>Provide complete address for dispatch riders</HelperText>
        </FormGroup>

        {/* Digital Address with Auto-detect */}
        <FormGroup>
          <Label htmlFor="digitalAddress">
            <FaCompass /> Digital Address (Ghana Post GPS)
            <LocationButton
              type="button"
              onClick={getCurrentLocation}
              disabled={isFetchingLocation || isSubmitting}
            >
              <FaSearchLocation />
              {isFetchingLocation ? 'Detecting...' : 'Auto-detect'}
            </LocationButton>
          </Label>
          <Input
            id="digitalAddress"
            name="digitalAddress"
            type="text"
            value={formData.digitalAddress}
            onChange={handleChange}
            placeholder="GA-123-4567 (auto-generated from GPS)"
            maxLength={15}
            disabled={isSubmitting}
            style={{ textTransform: 'uppercase' }}
            readOnly
          />
          {locationError && <ErrorText>{locationError}</ErrorText>}
          <HelperText>
            Digital address will be automatically generated when you use "Auto-detect" or provide GPS coordinates
          </HelperText>
        </FormGroup>

        {/* Contact Person Name */}
        <FormGroup>
          <Label htmlFor="contactName">
            <FaUser /> Contact Person Name <Required>*</Required>
          </Label>
          <Input
            id="contactName"
            name="contactName"
            type="text"
            value={formData.contactName}
            onChange={handleChange}
            placeholder="Name of person to contact for pickup"
            disabled={isSubmitting}
            $hasError={!!errors.contactName}
          />
          {errors.contactName && <ErrorText>{errors.contactName}</ErrorText>}
        </FormGroup>

        {/* Contact Phone */}
        <FormGroup>
          <Label htmlFor="contactPhone">
            <FaPhone /> Contact Phone Number <Required>*</Required>
          </Label>
          <Input
            id="contactPhone"
            name="contactPhone"
            type="tel"
            value={formData.contactPhone}
            onChange={handleChange}
            placeholder="e.g., +233 24 123 4567 or 0241234567"
            disabled={isSubmitting}
            $hasError={!!errors.contactPhone}
          />
          {errors.contactPhone && <ErrorText>{errors.contactPhone}</ErrorText>}
          <HelperText>Phone number for dispatch riders to contact</HelperText>
        </FormGroup>

        {/* Default Location Toggle */}
        <FormGroup>
          <ToggleContainer>
            <ToggleInput
              type="checkbox"
              id="isDefault"
              name="isDefault"
              checked={formData.isDefault}
              onChange={handleChange}
              disabled={isSubmitting}
            />
            <ToggleLabel htmlFor="isDefault">
              Set as default pickup location
            </ToggleLabel>
          </ToggleContainer>
          <HelperText>
            The default location will be used for order pickups unless you specify otherwise
          </HelperText>
        </FormGroup>

        {/* Notes (Optional) */}
        <FormGroup>
          <Label htmlFor="notes">
            <FaStickyNote /> Additional Notes (Optional)
          </Label>
          <TextArea
            id="notes"
            name="notes"
            value={formData.notes}
            onChange={handleChange}
            placeholder="Any additional information for dispatch riders (e.g., operating hours, special instructions)"
            rows={3}
            disabled={isSubmitting}
          />
          <HelperText>Optional: Add any special instructions or information</HelperText>
        </FormGroup>

        {/* Form Actions */}
        <FormActions>
          {onCancel && (
            <Button
              type="button"
              variant="outline"
              onClick={onCancel}
              disabled={isSubmitting}
            >
              Cancel
            </Button>
          )}
          <Button
            type="submit"
            variant="primary"
            disabled={isSubmitting}
          >
            {isSubmitting ? 'Saving...' : initialData ? 'Update Location' : 'Create Location'}
          </Button>
        </FormActions>
      </StyledForm>
    </FormContainer>
  );
};

export default PickupLocationForm;

// Styled Components
const FormContainer = styled.div`
  width: 100%;
  max-width: 800px;
`;

const StyledForm = styled.form`
  display: flex;
  flex-direction: column;
  gap: var(--spacing-lg);
`;

const FormGroup = styled.div`
  display: flex;
  flex-direction: column;
  gap: var(--spacing-xs);
`;

const Label = styled.label`
  display: flex;
  align-items: center;
  gap: var(--spacing-xs);
  font-size: var(--font-size-sm);
  font-weight: var(--font-semibold);
  color: var(--color-grey-700);
  
  svg {
    color: var(--color-grey-500);
    font-size: var(--font-size-sm);
  }
`;

const Required = styled.span`
  color: var(--color-red-600);
`;

const Input = styled.input`
  width: 100%;
  padding: var(--spacing-sm) var(--spacing-md);
  border: 1px solid ${props => props.$hasError ? 'var(--color-red-500)' : 'var(--color-grey-300)'};
  border-radius: var(--border-radius-md);
  font-size: var(--font-size-md);
  font-family: var(--font-body);
  color: var(--color-grey-900);
  background-color: var(--color-white-0);
  transition: all var(--transition-base);

  &:focus {
    outline: none;
    border-color: ${props => props.$hasError ? 'var(--color-red-500)' : 'var(--color-primary-500)'};
    box-shadow: 0 0 0 3px ${props => props.$hasError ? 'var(--color-red-100)' : 'var(--color-primary-100)'};
  }

  &:disabled {
    background-color: var(--color-grey-100);
    cursor: not-allowed;
    opacity: 0.6;
  }

  &::placeholder {
    color: var(--color-grey-400);
  }
`;

const TextArea = styled.textarea`
  width: 100%;
  padding: var(--spacing-sm) var(--spacing-md);
  border: 1px solid ${props => props.$hasError ? 'var(--color-red-500)' : 'var(--color-grey-300)'};
  border-radius: var(--border-radius-md);
  font-size: var(--font-size-md);
  font-family: var(--font-body);
  color: var(--color-grey-900);
  background-color: var(--color-white-0);
  transition: all var(--transition-base);
  resize: vertical;

  &:focus {
    outline: none;
    border-color: ${props => props.$hasError ? 'var(--color-red-500)' : 'var(--color-primary-500)'};
    box-shadow: 0 0 0 3px ${props => props.$hasError ? 'var(--color-red-100)' : 'var(--color-primary-100)'};
  }

  &:disabled {
    background-color: var(--color-grey-100);
    cursor: not-allowed;
    opacity: 0.6;
  }

  &::placeholder {
    color: var(--color-grey-400);
  }
`;

const ToggleContainer = styled.div`
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  padding: var(--spacing-sm);
`;

const ToggleInput = styled.input`
  width: 2rem;
  height: 2rem;
  cursor: pointer;
  accent-color: var(--color-primary-500);

  &:disabled {
    cursor: not-allowed;
    opacity: 0.6;
  }
`;

const ToggleLabel = styled.label`
  font-size: var(--font-size-md);
  font-weight: var(--font-medium);
  color: var(--color-grey-700);
  cursor: pointer;
  user-select: none;
`;

const ErrorText = styled.span`
  font-size: var(--font-size-xs);
  color: var(--color-red-600);
  margin-top: calc(var(--spacing-xs) * -1);
`;

const HelperText = styled.span`
  font-size: var(--font-size-xs);
  color: var(--color-grey-600);
  margin-top: calc(var(--spacing-xs) * -1);
`;

const FormActions = styled.div`
  display: flex;
  gap: var(--spacing-md);
  justify-content: flex-end;
  margin-top: var(--spacing-md);
  padding-top: var(--spacing-lg);
  border-top: 1px solid var(--color-grey-200);

  @media (max-width: 768px) {
    flex-direction: column-reverse;
    
    button {
      width: 100%;
    }
  }
`;

const LocationButton = styled.button`
  display: inline-flex;
  align-items: center;
  gap: var(--spacing-xs);
  padding: var(--spacing-xs) var(--spacing-sm);
  margin-left: var(--spacing-sm);
  background-color: var(--color-primary-500);
  color: var(--color-white-0);
  border: none;
  border-radius: var(--border-radius-sm);
  font-size: var(--font-size-xs);
  font-weight: var(--font-medium);
  cursor: pointer;
  transition: all var(--transition-base);

  &:hover:not(:disabled) {
    background-color: var(--color-primary-600);
    transform: translateY(-1px);
  }

  &:disabled {
    background-color: var(--color-grey-400);
    cursor: not-allowed;
    opacity: 0.6;
  }

  svg {
    font-size: var(--font-size-sm);
  }
`;

